---
version: '3'

services:
  db:
    image: postgres:15.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command:
      bash
    tty: true
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings

volumes:
  db-data:
