version: '3'
services:
  db:
    image: postgres:15.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command:
      bash
    tty: true
    depends_on:
      - db
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      CELERY_BROKER: redis://redis:6379/0
      CELERY_BACKEND: redis://redis:6379/0

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  redis:
    image: "redis:alpine"

volumes:
  db-data:
