# Generated by Django 4.2.4 on 2023-09-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garancija', '0003_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warranty',
            name='active',
        ),
        migrations.RemoveField(
            model_name='warranty',
            name='shop',
        ),
        migrations.AlterField(
            model_name='warranty',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='start_date',
            field=models.DateField(),
        ),
    ]
