# Generated by Django 4.2.4 on 2023-10-24 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garancija', '0004_remove_warranty_active_remove_warranty_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesperson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
