# Generated by Django 4.2.4 on 2023-11-01 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garancija', '0006_warranty_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warranties', to=settings.AUTH_USER_MODEL),
        ),
    ]
