# Generated by Django 4.2.4 on 2024-01-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garancija', '0007_alter_warranty_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
