# Generated by Django 4.2.4 on 2023-10-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garancija', '0005_alter_warranty_salesperson_delete_employee'),
        ('user', '0004_alter_user_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='garancija.shop'),
        ),
    ]
