# Generated by Django 4.2.4 on 2023-11-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_warranty', 'can_view_warranty'), ('can_create_warranty', 'can_create_warranty'), ('can_edit_warranty', 'can_edit_warranty'), ('can_delete_warranty', 'can_delete_warranty')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
