# Generated by Django 4.2.4 on 2023-11-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_create_warranty', 'can_create_warranty'), ('can_edit_warranty', 'can_edit_warranty'), ('can_delete_warranty', 'can_delete_warranty'), ('can_view_my_warranty', 'can_view_my_warranty'), ('can_view_shop_warranty', 'can_view_shop_warranty'), ('can_view_customer', 'can_view_customer'), ('can_view_shop_employee', 'can_view_shop_employee')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
