---
# yamllint disable-line rule:truthy
on:
  push:
    paths:
      - '*'
name: flake8
jobs:
  flake8-lint:
    runs-on: ubuntu-20.04
    name: flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: x64
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: '120'